aplicacion_bancaria/aplicacion_bancaria/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('usuarios.urls')),
    url(r'^', include('banco.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aplicacion_bancaria/banco/urls.py
from django.conf.urls import url
from banco.views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^bancos/$', login_required(InicioView.as_view()), name="bancos"),
	url(r'^bancos/clientes/$', login_required(ClientesView.as_view()), name="clientes"),
	url(r'^bancos/transacciones/$', login_required(TransaccionesView.as_view()), name="transacciones"),
]

aplicacion_bancaria/banco/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from usuarios.models import Usuario
from django.db.models import Sum
import json

class ModeloBase(models.Model):

   fecha_registro = models.DateTimeField(auto_now_add=True)
   usuario_registro = models.ForeignKey(Usuario)
   estado_registro = models.BooleanField(default=True)
   observaciones = models.TextField(null=True,blank=True)

   class Meta:
      abstract = True

class Banco(ModeloBase):
   codigo = models.CharField(max_length=4,unique=True)
   nombre = models.CharField(max_length=250)
   direccion = models.CharField(max_length=250)

   def to_json(self):
      return {
         "id":self.id,
         "codigo":self.codigo,
         "nombre":self.nombre,
         "direccion":self.direccion,
         "usuario":unicode(self.usuario_registro),
         "fecha_registro":self.fecha_registro.strftime("%Y-%m-%d")
      }

   def get_clientes(self):
      return self.cliente_set.filter(estado_registro=True)

   def __unicode__(self):
      return unicode(self.codigo)+" - "+unicode(self.nombre)

class Cliente(ModeloBase):
   documento = models.CharField(max_length=50,unique=True)
   nombre = models.CharField(max_length=250)
   direccion = models.CharField(max_length=250)
   fecha_nacimiento = models.DateField()
   banco = models.ForeignKey(Banco)

   def get_cuentas(self):
      return self.cuenta_set.filter(estado_registro=True)

   def get_historial_transacciones(self):
      directas = Transaccion.objects.filter(cuenta__cliente=self)
      ids_directas = directas.values_list("id",flat=True)
      directas = list(directas)
      indirectas = list(Transaccion.objects.filter(cuenta_destino__cliente=self).exclude(pk__in=ids_directas))
      directas.extend(indirectas)
      return directas

   def get_json_cuentas(self):
      info = []
      cuentas = self.cuenta_set.filter(estado_registro=True)
      for c in cuentas:
         info.append({
            "id":c.id,
            "nombre_tipo_cuenta":c.get_tipo_display(),
            "numero_cuenta":c.numero_cuenta,
            "numero_tarjeta":c.get_tarjeta_debito().numero,
            "tipo_cuenta":c.tipo
         })
      return json.dumps(info)

   def __unicode__(self):
      return unicode(self.nombre)

class Cuenta(ModeloBase):
   AHORROS = 1
   CORRIENTE = 2
   OTRA = 3

   TIPOS_DE_CUENTAS = (
      (AHORROS,'Ahorros'),
      (CORRIENTE,'Corriente'),
      (OTRA,'Otra'),
   )
   cliente = models.ForeignKey(Cliente)
   tipo = models.SmallIntegerField(choices=TIPOS_DE_CUENTAS,default=AHORROS)
   numero_cuenta = models.CharField(max_length=30)

   def get_saldo(self):
      # entradas 
      valor = Transaccion.objects.filter(cuenta=self,tipo=Transaccion.CONSIGNACION).aggregate(Sum('valor'))['valor__sum'] or 0
      valor += Transaccion.objects.filter(cuenta_destino=self,tipo=Transaccion.TRANSFERENCIA).aggregate(Sum('valor'))['valor__sum'] or 0
      # salidas
      valor -= Transaccion.objects.filter(cuenta=self,tipo=Transaccion.RETIRO).aggregate(Sum('valor'))['valor__sum'] or 0
      valor -= Transaccion.objects.filter(cuenta=self,tipo=Transaccion.TRANSFERENCIA).aggregate(Sum('valor'))['valor__sum'] or 0
      return round(valor,2)

   def get_tarjeta_debito(self):
      tarjeta = self.tarjetadebito_set.filter(estado_registro=True).order_by('-fecha_registro')
      return tarjeta[0] if tarjeta else None

   def __unicode__(self):
      return unicode(self.cliente)+" - "+unicode(self.numero_cuenta)

class TarjetaDebito(ModeloBase):
   numero = models.CharField(max_length=30,unique=True)
   cuenta = models.ForeignKey(Cuenta)

   def save(self):
      if not self.id:
         tarjetas = self.cuenta.tarjetadebito_set.all()
         for t in  tarjetas:
            t.estado_registro= False
            t.save()
      super(TarjetaDebito,self).save()

   def __unicode__(self):
      return unicode(self.cuenta)+" - "+unicode(self.numero) 

class Transaccion(ModeloBase):
   TRANSFERENCIA = 1
   CONSIGNACION = 2
   RETIRO = 3
   TIPOS_TRANSACCION = (
      (TRANSFERENCIA,'Transeferencia'),
      (CONSIGNACION,'Consignación'),
      (RETIRO,'Retiro'),
   )
   banco = models.ForeignKey(Banco)
   tipo = models.SmallIntegerField(choices=TIPOS_TRANSACCION)
   cuenta = models.ForeignKey(Cuenta,related_name='cuenta')
   cuenta_destino = models.ForeignKey(Cuenta,related_name='cuenta_destino',null=True,blank=True)
   valor = models.FloatField()

   def get_clase(self,cliente=None):
      if self.tipo == self.RETIRO:
         return 'valor_negativo'
      if self.tipo == self.CONSIGNACION:
         return 'valor_positivo'
      if self.tipo == self.TRANSFERENCIA:
         if cliente:
            if self.cuenta_destino.cliente == cliente:
               return 'valor_positivo'
            return 'valor_negativo'
         return "valor_neutro"

   def __unicode__(self):
      return unicode(self.get_tipo_display())+" - "+unicode(self.cuenta)

aplicacion_bancaria/banco/forms.py
# -*- coding: utf-8 -*-
from django import forms
from banco.models import *
import json
from django.contrib.humanize.templatetags.humanize import intcomma

class BancoForm(forms.ModelForm):

   def clean_codigo(self):
      return self.cleaned_data.get("codigo").upper()

   class Meta:
      model = Banco
      exclude = ('usuario_registro','fecha_registro','estado_registro',)

class ClienteForm(forms.ModelForm):

   tipo_cuenta = forms.ChoiceField(choices=Cuenta.TIPOS_DE_CUENTAS)
   cuentas = forms.CharField(initial='[]',widget=forms.HiddenInput)

   def __init__(self, *args, **kwargs):
     self.banco = kwargs.pop("banco",None)
     super(ClienteForm, self).__init__(*args, **kwargs)

   def clean_cuentas(self):
      cuentas = json.loads(self.cleaned_data.get("cuentas") or "[]")
      info = []
      eliminar = []
      for c in cuentas:
         if 'id' in c:
            if "eliminada" in c:
               eliminar.append(Cuenta.objects.get(pk=c["id"]))
         else:
            tipo_cuenta = int(c["tipo_cuenta"])
            cuenta = c["numero_cuenta"].upper()
            tarjeta = c["numero_tarjeta"].upper()

            existe = Cuenta.objects.filter(estado_registro=True,numero_cuenta=cuenta,tipo=tipo_cuenta,cliente__banco=self.banco)
            if existe:
               raise forms.ValidationError("La cuenta numero "+cuenta+" ya se encuentra registrada.")
            existe = TarjetaDebito.objects.filter(estado_registro=True,numero=tarjeta,cuenta__cliente__banco=self.banco)
            if existe:
               raise forms.ValidationError("La tarjeta numero "+tarjeta+" ya se encuentra registrada.")

            info.append({
               "cuenta": Cuenta(tipo=tipo_cuenta,numero_cuenta= cuenta),
               "tarjeta": TarjetaDebito(numero=tarjeta)
            })
      if self.instance.id:
         return info, eliminar
      return info


   class Meta:
      model = Cliente
      exclude = ('usuario_registro','fecha_registro','estado_registro','banco')

class TransaccionForm(forms.ModelForm):

   def clean(self):
      cleaned_data = super(TransaccionForm,self).clean()
      if cleaned_data.get("tipo") == Transaccion.TRANSFERENCIA:
         if not cleaned_data.get("cuenta_destino"):
            raise forms.ValidationError("Debe ingresarse la cuenta destino de la transferencia")
         if cleaned_data.get("cuenta") == cleaned_data.get("cuenta_destino"):
            raise forms.ValidationError("No se puede realizar una transferencia entre la misma cuenta")
      else:
         cleaned_data["cuenta_destino"] = None

      if cleaned_data.get("valor") <=0:
         raise forms.ValidationError("El valor de la transacción debe ser mayor a 0")

      # Validar efectividad de transaccion
      if cleaned_data.get("tipo") == Transaccion.TRANSFERENCIA or cleaned_data.get("tipo") == Transaccion.RETIRO:
         saldo = cleaned_data.get("cuenta").get_saldo()
         if saldo < cleaned_data.get("valor"):
            raise forms.ValidationError("La cuenta "+unicode(cleaned_data.get("cuenta"))+" no tiene saldo suficiente. (Saldo: "+intcomma(saldo)+")")

      return cleaned_data
      

   class Meta:
      model = Transaccion
      exclude = ('usuario_registro','fecha_registro','estado_registro',)
    
class TarjetaDebitoForm(forms.ModelForm):
   class Meta:
      model = TarjetaDebito
      exclude = ('usuario_registro','fecha_registro','estado_registro')
      widgets = {
         "cuenta": forms.HiddenInput,
      }
    

aplicacion_bancaria/banco/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from banco.models import *
from forms import *
# Create your views here.
class InicioView(View):

   def agregar(self,request):
      formulario = BancoForm(request.POST)
      if formulario.is_valid():
         banco = formulario.save(commit=False)
         banco.usuario_registro = request.user
         banco.save()
         bancos = Banco.objects.filter(estado_registro=True)
         return render(request, 'render/tabla_bancos.html', locals())
      if formulario.errors:
         return JsonResponse({"mensaje":unicode(formulario.errors)}) 
      return render(request, 'inicio.html', locals())

   def eliminar_banco(self,request):
      banco = get_object_or_404(Banco,pk=request.POST["eliminar_banco"])
      banco.delete()
      bancos = Banco.objects.filter(estado_registro=True)
      return render(request, 'render/tabla_bancos.html', locals())

   def validar_codigo(self,request):
      codigo = request.POST["validar_codigo"].upper()
      if Banco.objects.filter(codigo=codigo):
         return HttpResponse("El codigo "+unicode(codigo)+" ya se encuentra registrado",status=500)
      return HttpResponse("El codigo "+unicode(codigo)+" esta disponible")

   def get(self,request):
      formulario = BancoForm()
      bancos = Banco.objects.filter(estado_registro=True)
      return render(request, 'inicio.html', locals())

   def post(self,request):
      if 'agregar_banco' in request.POST and 'banco.add_banco' in request.user.get_all_permissions():
         return self.agregar(request)
      if 'validar_codigo' in request.POST:
         return self.validar_codigo(request)
      if 'eliminar_banco' in request.POST and 'banco.delete_banco' in request.user.get_all_permissions():
         return self.eliminar_banco(request)
      return HttpResponse("No posee los permisos para esta funcion",status=403)

class ClientesView(View):

   def agregar(self,request,banco):
      formulario = ClienteForm(request.POST or None, banco=banco)
      if formulario.is_valid():
         cliente = formulario.save(commit=False)
         cliente.banco = banco
         cliente.usuario_registro = request.user
         cliente.save()
         # Cuentas
         for item in formulario.cleaned_data.get("cuentas"):
            # Cuenta
            item["cuenta"].cliente = cliente
            item["cuenta"].usuario_registro = request.user
            item["cuenta"].save()
            # Tarjeta
            item["tarjeta"].cuenta= item["cuenta"]
            item["tarjeta"].usuario_registro = request.user
            item["tarjeta"].save()
         return HttpResponseRedirect("/bancos/clientes?banco="+str(banco.id)+"&ver_cliente="+str(cliente.id))

      return render(request, 'clientes/agregar_nuevo_cliente.html', locals())

   def ver(self,request,banco):
      cliente = get_object_or_404(Cliente,pk=request.GET['ver_cliente'])
      formulario = TarjetaDebitoForm(request.POST or None)
      if formulario.is_valid():
         tarjeta = formulario.save(commit=False)
         tarjeta.usuario_registro= request.user
         tarjeta.save()
         return HttpResponseRedirect("/bancos/clientes/?banco="+str(banco.id)+"&ver_cliente="+str(cliente.id))
      return render(request, 'clientes/ver_cliente.html', locals())

   def editar(self,request,banco):
      cliente = get_object_or_404(Cliente,pk=request.GET["editar"])
      formulario = ClienteForm(request.POST or None, banco=banco,instance=cliente)
      if formulario.is_valid():
         cliente = formulario.save()
         # Cuentas
         nuevas_cuentas, eliminadas = formulario.cleaned_data.get("cuentas")
         for item in nuevas_cuentas:
            # Cuenta
            item["cuenta"].cliente = cliente
            item["cuenta"].usuario_registro = request.user
            item["cuenta"].save()
            # Tarjeta
            item["tarjeta"].cuenta= item["cuenta"]
            item["tarjeta"].usuario_registro = request.user
            item["tarjeta"].save()
         for el in eliminadas:
            el.estado_registro= False
            el.save()
         return HttpResponseRedirect("/bancos/clientes?banco="+str(banco.id)+"&ver_cliente="+str(cliente.id))
      return render(request, 'clientes/agregar_nuevo_cliente.html', locals())

   def eliminar(self,request,banco):
      cliente = get_object_or_404(Cliente,pk=request.GET["eliminar"])
      cliente.estado_registro= False
      cliente.save()
      return HttpResponseRedirect("/bancos/clientes/?banco="+str(banco.id))

   def get(self,request):
      banco = get_object_or_404(Banco,pk=request.GET["banco"])
      if 'eliminar' in request.GET:
         return self.eliminar(request,banco)
      if 'agregar' in request.GET and 'banco.add_cliente' in request.user.get_all_permissions():
         return self.agregar(request,banco)
      if 'editar' in request.GET and 'banco.change_cliente' in request.user.get_all_permissions():
         return self.editar(request,banco)
      if 'ver_cliente' in request.GET:
         return self.ver(request,banco)
      clientes = Cliente.objects.filter(estado_registro=True,banco=banco)
      return render(request, 'clientes/listado_clientes.html', locals())
      
   def post(self,request):
      banco = get_object_or_404(Banco,pk=request.GET["banco"])
      if 'agregar' in request.GET and 'banco.add_cliente' in request.user.get_all_permissions():
         return self.agregar(request,banco)
      if 'editar' in request.GET and 'banco.change_cliente' in request.user.get_all_permissions():
         return self.editar(request,banco)
      if 'ver_cliente' in request.GET:
         return self.ver(request,banco)
      return HttpResponse("No posee los permisos para esta funcion",status=403)

class TransaccionesView(View):

   def agregar(self,request):
      formulario = TransaccionForm(request.POST or None)
      if formulario.is_valid():
         transaccion = formulario.save(commit=False)
         transaccion.usuario_registro =request.user
         transaccion.save()
         return HttpResponseRedirect("/bancos/transacciones/")
      return render(request, 'transacciones/agregar_transaccion.html', locals())

   def get(self,request):
      if 'agregar' in request.GET:
         return self.agregar(request)
      transacciones = Transaccion.objects.filter(estado_registro=True).order_by('-fecha_registro')
      return render(request, 'transacciones/listado_transacciones.html', locals())
      
   def get_cuentas_banco(self,request):
      info = []
      banco = get_object_or_404(Banco,pk=request.POST['get_cuentas_banco'])
      cuentas = Cuenta.objects.filter(cliente__banco=banco,estado_registro=True)
      for c in cuentas:
         info.append({
            "id":c.id,
            "nombre":unicode(c)
         })
      return JsonResponse({'info':info})

   def post(self,request):
      if 'agregar' in request.GET:
         return self.agregar(request)
      if 'get_cuentas_banco' in request.POST:
         return self.get_cuentas_banco(request)
      return HttpResponse("No posee los permisos para esta funcion",status=403)

aplicacion_bancaria/banco/templates/transacciones/agregar_transaccion.html
{% extends "layout.html" %}
{% load filtros_usuarios %}
{% block titulo %}
	Agregar nueva transacción
{% endblock titulo %}
{% block css %}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.7.0/chosen.min.css">
{% endblock css %}
{% block contenido %}
	<div class="page-heading">
		<h1>
			<i class="fa fa-exchange" aria-hidden="true"></i> Agregar nueva transacción
		</h1>
	</div>
	{% if formulario.errors %}
		<div class="alert alert-danger">
			<strong><i class="fa fa-info-circle"></i> Atención!. </strong>Se han detectado los siguientes inconvenientes: <br>
			{{formulario.errors}}
		</div>
	{% endif %}
	<form method="post" action="">
		{% csrf_token %}
		<div class="row">
			<div class="col-sm-12">
				<button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Guardar</button>
			</div>
		</div>
		<div class="widget">
			<div class="widget-header">
				<h2><strong>Favor complete el siguente formulario</strong></h2>
			</div>
			<div class="widget-content padding">
				<div class="row">
					<div class="col-sm-6">
						<label for="{{formulario.banco.id_for_label}}">{{formulario.banco.label_tag}}*</label>
						{{formulario.banco|addclass:"form-control"}}
					</div>
					<div class="col-sm-6">
						<label for="{{formulario.tipo.id_for_label}}">{{formulario.tipo.label_tag}}*</label>
						{{formulario.tipo|addclass:"form-control"}}
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-sm-6">
						<label for="{{formulario.cuenta.id_for_label}}">{{formulario.cuenta.label_tag}}*</label>
						{{formulario.cuenta|addclass:"form-control"}}
					</div>
					<div class="col-sm-6">
						<label for="{{formulario.valor.id_for_label}}">{{formulario.valor.label_tag}}*</label>
						{{formulario.valor|addclass:"form-control"}}
					</div>
				</div>
				<br>
				<div class="row" id="cuenta_destino" style="display:none">
					<div class="col-sm-6">
						<label for="{{formulario.cuenta_destino.id_for_label}}">{{formulario.cuenta_destino.label_tag}}*</label>
						{{formulario.cuenta_destino|addclass:"form-control"}}
					</div>
				</div>
			</div>
		</div>
	</form>
{% endblock contenido %}
{% block js %}
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.7.0/chosen.jquery.min.js"></script>
	<script type="text/javascript">
		const TRANSFERENCIA = 1;

		$("select").chosen({"width":'100%'});

		window.onload = function() {
			$("select[name=banco]").change();
			$("select[name=tipo]").change();
		};

		$(document).on('change', 'select[name=banco]', function(event) {
			var banco = $(this).val();
			if(banco){
				$.ajax({
					url: '{% url "transacciones" %}',
					type: 'POST',
					dataType: 'json',
					data: {'get_cuentas_banco': banco},
					success:function(data) {
						var data = data["info"];
						var html ='<option value="">--------</option>';
						for (var i = 0; i < data.length; i++) {
							html += '<option value="'+data[i]["id"]+'">'+data[i]["nombre"]+'</option>';
						}
						$("select[name=cuenta]").html(html);
						$("select[name=cuenta_destino]").html(html);
						$("select").trigger('chosen:updated');
					}
				});
				
			}else{
				//$("select[name=cuenta]").val("");
				//$("select[name=cuenta_destino]").val("");
				$("select[name=cuenta]").html("");
				$("select[name=cuenta_destino]").html("");
				$("select").trigger('chosen:updated');
			}
		});		

		

		$(document).on('change', 'select[name=tipo]', function(event) {
			var tipo = parseInt($(this).val() || "0");
			$("#cuenta_destino").hide();
			if(tipo==TRANSFERENCIA){
				$("#cuenta_destino").show();
			}
		});

		

		$("#link_transacciones").addClass('active');
	</script>
{% endblock js %}

aplicacion_bancaria/banco/templates/transacciones/listado_transacciones.html
{% extends "layout.html" %}
{% load humanize %}
{% block titulo %}
	Transacciones
{% endblock titulo %}
{% block css %}
	<link href="/static/assets/libs/jquery-datatables/css/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
	<link href="/static/assets/libs/jquery-datatables/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet" type="text/css" />
{% endblock css %}
{% block contenido %}
	<div class="page-heading">
		<h1>
			<i class="fa fa-exchange" aria-hidden="true"></i> Transacciones
			{% if perms.banco.add_transaccion %}
				<a href="{% url 'transacciones' %}?agregar" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Agregar nueva transacción</a>
			{% endif %}
		</h1>
	</div>

	<div class="widget">
		<div class="widget-header">
			<h2><strong>Listado transacciones registradas</strong></h2>
		</div>
		<div class="widget-content">
			<div class="table-responsive">
				<table class="table table-bordered table-condensed datatable">
					<thead>
						<tr>
							<th>No.</th>
							<th>Fecha</th>
							<th>Banco</th>
							<th>Tipo</th>
							<th>Valor</th>
							<th>Cuenta</th>
							<th>Cuenta Destino</th>
							<th>Usuario registró</th>
						</tr>
					</thead>
					<tbody>
						{% for transaccion in transacciones %}
							<tr>
								<td>{{transaccion.id}}</td>
								<td>{{transaccion.fecha_registro}}</td>
								<td>
									<a href="{% url 'clientes' %}?banco={{transaccion.banco_id}}" target="_blank"><i class="fa fa-external-link"></i> {{transaccion.banco}}</a>
								</td>
								<td>{{transaccion.get_tipo_display}}</td>
								<td class="right {{transaccion.get_clase}}">{{transaccion.valor|intcomma}}</td>
								<td>
									<a href="{% url 'clientes' %}?banco={{transaccion.banco_id}}&ver_cliente={{transaccion.cuenta.cliente_id}}" target="_blank"><i class="fa fa-external-link"></i> {{transaccion.cuenta}}</a>
								</td>
								<td>
									{% if transaccion.cuenta_destino %}
										<a href="{% url 'clientes' %}?banco={{transaccion.banco_id}}&ver_cliente={{transaccion.cuenta_destino.cliente_id}}" target="_blank"><i class="fa fa-external-link"></i> {{transaccion.cuenta_destino}}</a>
									{% endif %}
								</td>
								<td>{{transaccion.usuario_registro}}</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
{% endblock contenido %}
{% block js %}
	<script src="/static/assets/libs/jquery-datatables/js/jquery.dataTables.min.js"></script>
	<script src="/static/assets/libs/jquery-datatables/js/dataTables.bootstrap.js"></script>
	<script src="/static/assets/libs/jquery-datatables/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
	<script type="text/javascript">
		$("#link_transacciones").addClass('active');

		var configuracion_datatables= {"language": {
	            "emptyTable":     "No hay registros",
	            "info":           "Mostrando _START_ a _END_ de _TOTAL_ registros",
	            "infoEmpty":      "Mostrando 0 a 0 de 0 registros",
	            "infoFiltered":   "(Filtrado de _MAX_ de los registros totales)",
	            "infoPostFix":    "",
	            "thousands":      ",",
	            "lengthMenu":     "Mostrando _MENU_ registros",
	            "loadingRecords": "Cargando...",
	            "processing":     "Procesando...",
	            "search":         "Buscar:",
	            "zeroRecords":    "No se encontraron resultados",
	            "paginate": {
	                "first":      "Primero",
	                "last":       "Último",
	                "next":       "Siguiente",
	                "previous":   "Anterior"
	            },
	            "aria": {
	                "sortAscending":  ": activate to sort column ascending",
	                "sortDescending": ": activate to sort column descending"
	            }
	        },
	        "order":[[0,"desc"]]
	    	};

		
		var tabla_bancos = $(".datatable").DataTable(configuracion_datatables);

	</script>
{% endblock js %}	